[build]
  builder = "NIXPACKS"
  buildCommand = "npm --prefix server install && npm --prefix client install && npm --prefix client run build && rm -rf server/public && cp -r client/dist server/public"

[deploy]
  startCommand = "npm --prefix server start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5
